CREATE TABLE IF NOT EXISTS EDGES
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    thickness INTEGER                                 NOT NULL,
    min       FLOAT                                   NOT NULL,
    CONSTRAINT pk_edge PRIMARY KEY (id),
    CONSTRAINT UQ_EDGES UNIQUE (thickness)
);

CREATE TABLE IF NOT EXISTS BOTTOMS
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    volume    INTEGER                                 NOT NULL,
    name      VARCHAR,
    thickness INTEGER                                 NOT NULL,
    min       FLOAT                                   NOT NULL,
    edge_id   BIGINT,
    CONSTRAINT pk_bottom PRIMARY KEY (id),
    CONSTRAINT UQ_BOTTOMS UNIQUE (volume, thickness),
    CONSTRAINT FK_BOTTOMS_ON_EDGES FOREIGN KEY (edge_id) REFERENCES edges (id)
);

CREATE TABLE IF NOT EXISTS BELTS
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number    INTEGER                                 NOT NULL,
    thickness INTEGER                                 NOT NULL,
    min       FLOAT                                   NOT NULL,
    volume    INTEGER                                 NOT NULL,
    CONSTRAINT pk_belt PRIMARY KEY (id),
    CONSTRAINT UQ_BELTS UNIQUE (number, thickness, volume)
);

CREATE TABLE IF NOT EXISTS PIPELINE_NORMS
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type_id   BIGINT                                  NOT NULL,
    diameter  INTEGER                                 NOT NULL,
    thickness FLOAT                                   NOT NULL,
    min       FLOAT                                   NOT NULL,
    CONSTRAINT pk_pipelineNorm PRIMARY KEY (id),
    CONSTRAINT UQ_PIPELINE_NORMS UNIQUE (type_id, diameter, thickness)
);

CREATE TABLE IF NOT EXISTS PROTECTIONS
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    object_data_id BIGINT                                  NOT NULL,
    name           VARCHAR                                 NOT NULL,
    date           DATE,
    documentation  VARCHAR,
    CONSTRAINT pk_protection PRIMARY KEY (id),
    CONSTRAINT UQ_PROTECTIONS UNIQUE (name, documentation)
);

CREATE TABLE IF NOT EXISTS SURVEYS
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    object_data_id  BIGINT                                  NOT NULL,
    date            DATE                                    NOT NULL,
    survey          VARCHAR                                 NOT NULL,
    number          VARCHAR                                 NOT NULL,
    organization_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_survey PRIMARY KEY (id),
    CONSTRAINT UQ_SURVEYS UNIQUE (date, survey, number, organization_id)
);

CREATE TABLE IF NOT EXISTS REPAIRS
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    object_data_id  BIGINT                                  NOT NULL,
    date            DATE,
    description     VARCHAR,
    organization_id BIGINT,
    CONSTRAINT pk_repair PRIMARY KEY (id),
    CONSTRAINT UQ_REPAIRS UNIQUE (date, description, organization_id)
);

CREATE TABLE IF NOT EXISTS DIMENSIONS
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    height   INTEGER,
    length   INTEGER,
    diameter INTEGER,
    CONSTRAINT pk_dimension PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS PASSPORTS
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    type_id            BIGINT,
    object_data_id     BIGINT,
    author_id          BIGINT,
    project_number     VARCHAR,
    manufacturer_id    BIGINT,
    mounting_id        BIGINT,
    manufacture        VARCHAR,
    installation       DATE,
    operation          DATE,
    start_passport     DATE,
    dimension_id       BIGINT,
    height_pipe        FLOAT,
    protection_id      BIGINT,
    estimated_life     INTEGER,
    pressure           INTEGER,
    direct_pressure    VARCHAR,
    direct_temperature VARCHAR,
    back_pressure      VARCHAR,
    back_temperature   VARCHAR,
    temperature        VARCHAR,
    CONSTRAINT pk_passport PRIMARY KEY (id),
    CONSTRAINT UQ_PASSPORTS UNIQUE (object_data_id),
    CONSTRAINT FK_PASSPORTS_ON_DIMENSIONS FOREIGN KEY (dimension_id) REFERENCES dimensions (id),
    CONSTRAINT FK_PASSPORTS_ON_PROTECTIONS FOREIGN KEY (protection_id) REFERENCES protections (id)
);

CREATE TABLE IF NOT EXISTS PASSPORTS_BELTS
(
    passport_id BIGINT,
    belt_id     BIGINT,
    CONSTRAINT pk_passport_of_belts PRIMARY KEY (passport_id, belt_id)
);

CREATE TABLE IF NOT EXISTS PASSPORTS_BOTTOMS
(
    passport_id BIGINT,
    bottom_id   BIGINT,
    CONSTRAINT pk_passport_of_bottoms PRIMARY KEY (passport_id, bottom_id)
);

CREATE TABLE IF NOT EXISTS PASSPORTS_SURVEYS
(
    passport_id BIGINT,
    surveys_id  BIGINT,
    CONSTRAINT pk_passport_of_surveys PRIMARY KEY (passport_id, surveys_id)
);

CREATE TABLE IF NOT EXISTS PASSPORTS_REPAIRS
(
    passport_id BIGINT,
    repairs_id  BIGINT,
    CONSTRAINT pk_passport_of_repairs PRIMARY KEY (passport_id, repairs_id)
);

CREATE TABLE IF NOT EXISTS PASSPORTS_PIPELINE_NORMS
(
    passport_id      BIGINT,
    pipeline_norm_id BIGINT,
    CONSTRAINT pk_passport_of_pipeline_norms PRIMARY KEY (passport_id, pipeline_norm_id)
);